<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>Microsoft.Terminal.Wpf</AssemblyName>
    <RootNamespace>Microsoft.Terminal.Wpf</RootNamespace>
  </PropertyGroup>
</Project>
